# Generated by Django 3.1.4 on 2020-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20201216_1819'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(default=None, null=True, to='trading.Card'),
        ),
    ]
