# Generated by Django 3.1.4 on 2020-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201217_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(default='https://secure.gravatar.com/avatar/fcd55da13e2825cfeca3ed77022745ff?s=256&d=mm&r=g'),
        ),
    ]
