# Generated by Django 3.1.4 on 2020-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        ('account', '0003_auto_20201217_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(default=None, null=True, to='mainpage.Card'),
        ),
    ]
