# Generated by Django 3.1.4 on 2020-12-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.FloatField()),
                ('tcgplayer_price', models.FloatField()),
                ('ebay_price', models.FloatField()),
                ('amazon_price', models.FloatField()),
                ('coolstuffinc_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=255)),
                ('set_rarity', models.CharField(max_length=255)),
                ('set_rarity_code', models.CharField(max_length=255)),
                ('set_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('image_url', models.URLField()),
                ('image_url_small', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.archetype')),
                ('cardset', models.ManyToManyField(to='trading.Cardset')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.image')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.cardprice')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.race')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.type')),
            ],
        ),
    ]
