# Generated by Django 3.1.4 on 2020-12-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20201216_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_code',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_rarity',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_rarity_code',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=2550),
        ),
    ]
