# Generated by Django 3.1.4 on 2020-12-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201218_1327'),
        ('mainpage', '0001_initial'),
        ('trading', '0005_auto_20201216_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='archetype',
        ),
        migrations.RemoveField(
            model_name='card',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardset',
        ),
        migrations.RemoveField(
            model_name='card',
            name='race',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='card',
        ),
        migrations.RemoveField(
            model_name='image',
            name='card',
        ),
        migrations.DeleteModel(
            name='Archetype',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardPrice',
        ),
        migrations.DeleteModel(
            name='Cardset',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
