# Generated by Django 3.1.4 on 2020-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.ManyToManyField(to='todo_app.Todo'),
        ),
    ]
