# Generated by Django 3.1.4 on 2020-12-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201222_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.card'),
        ),
    ]
