# Generated by Django 3.1.4 on 2020-12-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20201222_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.image'),
        ),
    ]
